org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
kotlin.daemon.jvmargs=-Xmx1024m
kotlin.incremental=false
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false

# Fix for Windows cross-drive path error ("this and base files have different roots")
# Project is on D: drive while Flutter pub cache is on C: drive
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false

