org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false

# Fix for Windows cross-drive path error ("this and base files have different roots")
# Project is on D: drive while Flutter pub cache is on C: drive
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false

